AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'gemfiles/*'
    - '.git/**/*'
    - 'docs/**/*'

#
# Layout
#

# Match existing layout
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Match existing layout
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

# Phase 2:
# Layout/ClassStructure
#   Enabled: true

Layout/ConditionPosition:
  Enabled: true

# Match existing layout
Layout/DotPosition:
  AutoCorrect: true
  EnforcedStyle: trailing

Layout/EndAlignment:
  AutoCorrect: true

# Prevent accidental windows line endings
Layout/EndOfLine:
  EnforcedStyle: lf

# ForceEqualSignAlignment is broken, see https://github.com/rubocop-hq/rubocop/pull/5696
Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true
  AutoCorrect: true

# Pick one
Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Layout/RescueEnsureAlignment:
  AutoCorrect: true

# Rubocop cannot yet see beyond one line above or below, when aligning =
Layout/SpaceAroundOperators:
  AllowForAlignment: true
  AutoCorrect: true

# Match existing layout
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

# Files must end with a blank line
Layout/TrailingBlankLines:
  EnforcedStyle: final_newline

# TODO: Soften Limits for phase 1 only
Metrics/AbcSize:
  Max: 80

# Support long block lengths for tests
Metrics/BlockLength:
  Exclude:
  - '**/test/**/*'

# Soften limits
Metrics/ClassLength:
  Max: 250
  Exclude:
  - '**/test/**/*'

# TODO: Soften Limits for phase 1 only
Metrics/CyclomaticComplexity:
  Max: 15

# Soften limits
Metrics/LineLength:
  Max: 128
  Exclude:
  - 'cli.rb'
  - '**/test/**/*'

# Soften limits
Metrics/MethodLength:
  Max: 250

# Soften limits
Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  CountKeywordArgs: false

# TODO: Soften Limits for phase 1 only
Metrics/PerceivedComplexity:
  Max: 21

# ip is IP Address
Naming/UncommunicativeMethodParamName:
  AllowedNames:
  - ip
  - id
  - iv
  - _
  - io
  - ap

# Does not allow Symbols to load
Security/YAMLLoad:
  AutoCorrect: false

# TODO: Soften Limits for phase 1 only
Style/Documentation:
  Enabled: false

# One line methods
Style/EmptyMethod:
  EnforcedStyle: expanded

# Ruby 3 compatibility feature
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

# Incorrectly changes job.fail to job.raise
Style/SignalException:
  Enabled: false

# Since English may not be loaded, cannot force its use.
Style/SpecialGlobalVars:
  Enabled: false
